#define xaddq_u05 Sleef_addqx_u05sve
#define xsubq_u05 Sleef_subqx_u05sve
#define xmulq_u05 Sleef_mulqx_u05sve
#define xdivq_u05 Sleef_divqx_u05sve
#define xnegq Sleef_negqx_sve
#define xsqrtq_u05 Sleef_sqrtqx_u05sve
#define xcbrtq_u10 Sleef_cbrtqx_u10sve
#define xicmpltq Sleef_icmpltqx_sve
#define xicmpleq Sleef_icmpleqx_sve
#define xicmpgtq Sleef_icmpgtqx_sve
#define xicmpgeq Sleef_icmpgeqx_sve
#define xicmpeqq Sleef_icmpeqqx_sve
#define xicmpneq Sleef_icmpneqx_sve
#define xicmpq Sleef_icmpqx_sve
#define xiunordq Sleef_iunordqx_sve
#define xiselectq Sleef_iselectqx_sve
#define xcast_to_doubleq Sleef_cast_to_doubleqx_sve
#define xcast_from_doubleq Sleef_cast_from_doubleqx_sve
#define xcast_to_int64q Sleef_cast_to_int64qx_sve
#define xcast_from_int64q Sleef_cast_from_int64qx_sve
#define xcast_to_uint64q Sleef_cast_to_uint64qx_sve
#define xcast_from_uint64q Sleef_cast_from_uint64qx_sve
#define xloadq Sleef_loadqx_sve
#define xstoreq Sleef_storeqx_sve
#define xgetq Sleef_getqx_sve
#define xsetq Sleef_setqx_sve
#define xsplatq Sleef_splatqx_sve
#define xsinq_u10 Sleef_sinqx_u10sve
#define xcosq_u10 Sleef_cosqx_u10sve
#define xtanq_u10 Sleef_tanqx_u10sve
#define xasinq_u10 Sleef_asinqx_u10sve
#define xacosq_u10 Sleef_acosqx_u10sve
#define xatanq_u10 Sleef_atanqx_u10sve
#define xatan2q_u10 Sleef_atan2qx_u10sve
#define xexpq_u10 Sleef_expqx_u10sve
#define xexp2q_u10 Sleef_exp2qx_u10sve
#define xexp10q_u10 Sleef_exp10qx_u10sve
#define xexpm1q_u10 Sleef_expm1qx_u10sve
#define xlogq_u10 Sleef_logqx_u10sve
#define xlog2q_u10 Sleef_log2qx_u10sve
#define xlog10q_u10 Sleef_log10qx_u10sve
#define xlog1pq_u10 Sleef_log1pqx_u10sve
#define xpowq_u10 Sleef_powqx_u10sve
#define xsinhq_u10 Sleef_sinhqx_u10sve
#define xcoshq_u10 Sleef_coshqx_u10sve
#define xtanhq_u10 Sleef_tanhqx_u10sve
#define xasinhq_u10 Sleef_asinhqx_u10sve
#define xacoshq_u10 Sleef_acoshqx_u10sve
#define xatanhq_u10 Sleef_atanhqx_u10sve
#define xtruncq Sleef_truncqx_sve
#define xfloorq Sleef_floorqx_sve
#define xceilq Sleef_ceilqx_sve
#define xroundq Sleef_roundqx_sve
#define xrintq Sleef_rintqx_sve
#define xfabsq Sleef_fabsqx_sve
#define xcopysignq Sleef_copysignqx_sve
#define xfmaxq Sleef_fmaxqx_sve
#define xfminq Sleef_fminqx_sve
#define xfdimq_u05 Sleef_fdimqx_u05sve
#define xfmodq Sleef_fmodqx_sve
#define xremainderq Sleef_remainderqx_sve
#define xfrexpq Sleef_frexpqx_sve
#define xmodfq Sleef_modfqx_sve
#define xhypotq_u05 Sleef_hypotqx_u05sve
#define xldexpq Sleef_ldexpqx_sve
#define xilogbq Sleef_ilogbqx_sve
#define xfmaq_u05 Sleef_fmaqx_u05sve
