#define xaddq_u05 Sleef_addq1_u05cuda
#define xsubq_u05 Sleef_subq1_u05cuda
#define xmulq_u05 Sleef_mulq1_u05cuda
#define xdivq_u05 Sleef_divq1_u05cuda
#define xnegq Sleef_negq1_cuda
#define xsqrtq_u05 Sleef_sqrtq1_u05cuda
#define xcbrtq_u10 Sleef_cbrtq1_u10cuda
#define xicmpltq Sleef_icmpltq1_cuda
#define xicmpleq Sleef_icmpleq1_cuda
#define xicmpgtq Sleef_icmpgtq1_cuda
#define xicmpgeq Sleef_icmpgeq1_cuda
#define xicmpeqq Sleef_icmpeqq1_cuda
#define xicmpneq Sleef_icmpneq1_cuda
#define xicmpq Sleef_icmpq1_cuda
#define xiunordq Sleef_iunordq1_cuda
#define xiselectq Sleef_iselectq1_cuda
#define xcast_to_doubleq Sleef_cast_to_doubleq1_cuda
#define xcast_from_doubleq Sleef_cast_from_doubleq1_cuda
#define xcast_to_int64q Sleef_cast_to_int64q1_cuda
#define xcast_from_int64q Sleef_cast_from_int64q1_cuda
#define xcast_to_uint64q Sleef_cast_to_uint64q1_cuda
#define xcast_from_uint64q Sleef_cast_from_uint64q1_cuda
#define xloadq Sleef_loadq1_cuda
#define xstoreq Sleef_storeq1_cuda
#define xgetq Sleef_getq1_cuda
#define xsetq Sleef_setq1_cuda
#define xsplatq Sleef_splatq1_cuda
#define xsinq_u10 Sleef_sinq1_u10cuda
#define xcosq_u10 Sleef_cosq1_u10cuda
#define xtanq_u10 Sleef_tanq1_u10cuda
#define xasinq_u10 Sleef_asinq1_u10cuda
#define xacosq_u10 Sleef_acosq1_u10cuda
#define xatanq_u10 Sleef_atanq1_u10cuda
#define xatan2q_u10 Sleef_atan2q1_u10cuda
#define xexpq_u10 Sleef_expq1_u10cuda
#define xexp2q_u10 Sleef_exp2q1_u10cuda
#define xexp10q_u10 Sleef_exp10q1_u10cuda
#define xexpm1q_u10 Sleef_expm1q1_u10cuda
#define xlogq_u10 Sleef_logq1_u10cuda
#define xlog2q_u10 Sleef_log2q1_u10cuda
#define xlog10q_u10 Sleef_log10q1_u10cuda
#define xlog1pq_u10 Sleef_log1pq1_u10cuda
#define xpowq_u10 Sleef_powq1_u10cuda
#define xsinhq_u10 Sleef_sinhq1_u10cuda
#define xcoshq_u10 Sleef_coshq1_u10cuda
#define xtanhq_u10 Sleef_tanhq1_u10cuda
#define xasinhq_u10 Sleef_asinhq1_u10cuda
#define xacoshq_u10 Sleef_acoshq1_u10cuda
#define xatanhq_u10 Sleef_atanhq1_u10cuda
#define xtruncq Sleef_truncq1_cuda
#define xfloorq Sleef_floorq1_cuda
#define xceilq Sleef_ceilq1_cuda
#define xroundq Sleef_roundq1_cuda
#define xrintq Sleef_rintq1_cuda
#define xfabsq Sleef_fabsq1_cuda
#define xcopysignq Sleef_copysignq1_cuda
#define xfmaxq Sleef_fmaxq1_cuda
#define xfminq Sleef_fminq1_cuda
#define xfdimq_u05 Sleef_fdimq1_u05cuda
#define xfmodq Sleef_fmodq1_cuda
#define xremainderq Sleef_remainderq1_cuda
#define xfrexpq Sleef_frexpq1_cuda
#define xmodfq Sleef_modfq1_cuda
#define xhypotq_u05 Sleef_hypotq1_u05cuda
#define xldexpq Sleef_ldexpq1_cuda
#define xilogbq Sleef_ilogbq1_cuda
#define xfmaq_u05 Sleef_fmaq1_u05cuda
