#define xaddq_u05 Sleef_addq1_u05
#define xsubq_u05 Sleef_subq1_u05
#define xmulq_u05 Sleef_mulq1_u05
#define xdivq_u05 Sleef_divq1_u05
#define xnegq Sleef_negq1
#define xsqrtq_u05 Sleef_sqrtq1_u05
#define xcbrtq_u10 Sleef_cbrtq1_u10
#define xicmpltq Sleef_icmpltq1
#define xicmpleq Sleef_icmpleq1
#define xicmpgtq Sleef_icmpgtq1
#define xicmpgeq Sleef_icmpgeq1
#define xicmpeqq Sleef_icmpeqq1
#define xicmpneq Sleef_icmpneq1
#define xicmpq Sleef_icmpq1
#define xiunordq Sleef_iunordq1
#define xiselectq Sleef_iselectq1
#define xcast_to_doubleq Sleef_cast_to_doubleq1
#define xcast_from_doubleq Sleef_cast_from_doubleq1
#define xcast_to_int64q Sleef_cast_to_int64q1
#define xcast_from_int64q Sleef_cast_from_int64q1
#define xcast_to_uint64q Sleef_cast_to_uint64q1
#define xcast_from_uint64q Sleef_cast_from_uint64q1
#define xloadq Sleef_loadq1
#define xstoreq Sleef_storeq1
#define xgetq Sleef_getq1
#define xsetq Sleef_setq1
#define xsplatq Sleef_splatq1
#define xsinq_u10 Sleef_sinq1_u10
#define xcosq_u10 Sleef_cosq1_u10
#define xtanq_u10 Sleef_tanq1_u10
#define xasinq_u10 Sleef_asinq1_u10
#define xacosq_u10 Sleef_acosq1_u10
#define xatanq_u10 Sleef_atanq1_u10
#define xatan2q_u10 Sleef_atan2q1_u10
#define xexpq_u10 Sleef_expq1_u10
#define xexp2q_u10 Sleef_exp2q1_u10
#define xexp10q_u10 Sleef_exp10q1_u10
#define xexpm1q_u10 Sleef_expm1q1_u10
#define xlogq_u10 Sleef_logq1_u10
#define xlog2q_u10 Sleef_log2q1_u10
#define xlog10q_u10 Sleef_log10q1_u10
#define xlog1pq_u10 Sleef_log1pq1_u10
#define xpowq_u10 Sleef_powq1_u10
#define xsinhq_u10 Sleef_sinhq1_u10
#define xcoshq_u10 Sleef_coshq1_u10
#define xtanhq_u10 Sleef_tanhq1_u10
#define xasinhq_u10 Sleef_asinhq1_u10
#define xacoshq_u10 Sleef_acoshq1_u10
#define xatanhq_u10 Sleef_atanhq1_u10
#define xtruncq Sleef_truncq1
#define xfloorq Sleef_floorq1
#define xceilq Sleef_ceilq1
#define xroundq Sleef_roundq1
#define xrintq Sleef_rintq1
#define xfabsq Sleef_fabsq1
#define xcopysignq Sleef_copysignq1
#define xfmaxq Sleef_fmaxq1
#define xfminq Sleef_fminq1
#define xfdimq_u05 Sleef_fdimq1_u05
#define xfmodq Sleef_fmodq1
#define xremainderq Sleef_remainderq1
#define xfrexpq Sleef_frexpq1
#define xmodfq Sleef_modfq1
#define xhypotq_u05 Sleef_hypotq1_u05
#define xldexpq Sleef_ldexpq1
#define xilogbq Sleef_ilogbq1
#define xfmaq_u05 Sleef_fmaq1_u05
