#define xaddq_u05 Sleef_addq2_u05
#define xsubq_u05 Sleef_subq2_u05
#define xmulq_u05 Sleef_mulq2_u05
#define xdivq_u05 Sleef_divq2_u05
#define xnegq Sleef_negq2
#define xsqrtq_u05 Sleef_sqrtq2_u05
#define xcbrtq_u10 Sleef_cbrtq2_u10
#define xicmpltq Sleef_icmpltq2
#define xicmpleq Sleef_icmpleq2
#define xicmpgtq Sleef_icmpgtq2
#define xicmpgeq Sleef_icmpgeq2
#define xicmpeqq Sleef_icmpeqq2
#define xicmpneq Sleef_icmpneq2
#define xicmpq Sleef_icmpq2
#define xiunordq Sleef_iunordq2
#define xiselectq Sleef_iselectq2
#define xcast_to_doubleq Sleef_cast_to_doubleq2
#define xcast_from_doubleq Sleef_cast_from_doubleq2
#define xcast_to_int64q Sleef_cast_to_int64q2
#define xcast_from_int64q Sleef_cast_from_int64q2
#define xcast_to_uint64q Sleef_cast_to_uint64q2
#define xcast_from_uint64q Sleef_cast_from_uint64q2
#define xloadq Sleef_loadq2
#define xstoreq Sleef_storeq2
#define xgetq Sleef_getq2
#define xsetq Sleef_setq2
#define xsplatq Sleef_splatq2
#define xsinq_u10 Sleef_sinq2_u10
#define xcosq_u10 Sleef_cosq2_u10
#define xtanq_u10 Sleef_tanq2_u10
#define xasinq_u10 Sleef_asinq2_u10
#define xacosq_u10 Sleef_acosq2_u10
#define xatanq_u10 Sleef_atanq2_u10
#define xatan2q_u10 Sleef_atan2q2_u10
#define xexpq_u10 Sleef_expq2_u10
#define xexp2q_u10 Sleef_exp2q2_u10
#define xexp10q_u10 Sleef_exp10q2_u10
#define xexpm1q_u10 Sleef_expm1q2_u10
#define xlogq_u10 Sleef_logq2_u10
#define xlog2q_u10 Sleef_log2q2_u10
#define xlog10q_u10 Sleef_log10q2_u10
#define xlog1pq_u10 Sleef_log1pq2_u10
#define xpowq_u10 Sleef_powq2_u10
#define xsinhq_u10 Sleef_sinhq2_u10
#define xcoshq_u10 Sleef_coshq2_u10
#define xtanhq_u10 Sleef_tanhq2_u10
#define xasinhq_u10 Sleef_asinhq2_u10
#define xacoshq_u10 Sleef_acoshq2_u10
#define xatanhq_u10 Sleef_atanhq2_u10
#define xtruncq Sleef_truncq2
#define xfloorq Sleef_floorq2
#define xceilq Sleef_ceilq2
#define xroundq Sleef_roundq2
#define xrintq Sleef_rintq2
#define xfabsq Sleef_fabsq2
#define xcopysignq Sleef_copysignq2
#define xfmaxq Sleef_fmaxq2
#define xfminq Sleef_fminq2
#define xfdimq_u05 Sleef_fdimq2_u05
#define xfmodq Sleef_fmodq2
#define xremainderq Sleef_remainderq2
#define xfrexpq Sleef_frexpq2
#define xmodfq Sleef_modfq2
#define xhypotq_u05 Sleef_hypotq2_u05
#define xldexpq Sleef_ldexpq2
#define xilogbq Sleef_ilogbq2
#define xfmaq_u05 Sleef_fmaq2_u05
