#ifndef DETERMINISTIC

#define xsin Sleef_sindx_u35sve
#define ysin Sleef_finz_sindx_u35sve
#define xcos Sleef_cosdx_u35sve
#define ycos Sleef_finz_cosdx_u35sve
#define xsincos Sleef_sincosdx_u35sve
#define ysincos Sleef_finz_sincosdx_u35sve
#define xtan Sleef_tandx_u35sve
#define ytan Sleef_finz_tandx_u35sve
#define xasin Sleef_asindx_u35sve
#define yasin Sleef_finz_asindx_u35sve
#define xacos Sleef_acosdx_u35sve
#define yacos Sleef_finz_acosdx_u35sve
#define xatan Sleef_atandx_u35sve
#define yatan Sleef_finz_atandx_u35sve
#define xatan2 Sleef_atan2dx_u35sve
#define yatan2 Sleef_finz_atan2dx_u35sve
#define xlog Sleef_logdx_u35sve
#define ylog Sleef_finz_logdx_u35sve
#define xcbrt Sleef_cbrtdx_u35sve
#define ycbrt Sleef_finz_cbrtdx_u35sve
#define xsin_u1 Sleef_sindx_u10sve
#define ysin_u1 Sleef_finz_sindx_u10sve
#define xcos_u1 Sleef_cosdx_u10sve
#define ycos_u1 Sleef_finz_cosdx_u10sve
#define xsincos_u1 Sleef_sincosdx_u10sve
#define ysincos_u1 Sleef_finz_sincosdx_u10sve
#define xtan_u1 Sleef_tandx_u10sve
#define ytan_u1 Sleef_finz_tandx_u10sve
#define xasin_u1 Sleef_asindx_u10sve
#define yasin_u1 Sleef_finz_asindx_u10sve
#define xacos_u1 Sleef_acosdx_u10sve
#define yacos_u1 Sleef_finz_acosdx_u10sve
#define xatan_u1 Sleef_atandx_u10sve
#define yatan_u1 Sleef_finz_atandx_u10sve
#define xatan2_u1 Sleef_atan2dx_u10sve
#define yatan2_u1 Sleef_finz_atan2dx_u10sve
#define xlog_u1 Sleef_logdx_u10sve
#define ylog_u1 Sleef_finz_logdx_u10sve
#define xcbrt_u1 Sleef_cbrtdx_u10sve
#define ycbrt_u1 Sleef_finz_cbrtdx_u10sve
#define xexp Sleef_expdx_u10sve
#define yexp Sleef_finz_expdx_u10sve
#define xpow Sleef_powdx_u10sve
#define ypow Sleef_finz_powdx_u10sve
#define xsinh Sleef_sinhdx_u10sve
#define ysinh Sleef_finz_sinhdx_u10sve
#define xcosh Sleef_coshdx_u10sve
#define ycosh Sleef_finz_coshdx_u10sve
#define xtanh Sleef_tanhdx_u10sve
#define ytanh Sleef_finz_tanhdx_u10sve
#define xsinh_u35 Sleef_sinhdx_u35sve
#define ysinh_u35 Sleef_finz_sinhdx_u35sve
#define xcosh_u35 Sleef_coshdx_u35sve
#define ycosh_u35 Sleef_finz_coshdx_u35sve
#define xtanh_u35 Sleef_tanhdx_u35sve
#define ytanh_u35 Sleef_finz_tanhdx_u35sve
#define xfastsin_u3500 Sleef_fastsindx_u3500sve
#define yfastsin_u3500 Sleef_finz_fastsindx_u3500sve
#define xfastcos_u3500 Sleef_fastcosdx_u3500sve
#define yfastcos_u3500 Sleef_finz_fastcosdx_u3500sve
#define xfastpow_u3500 Sleef_fastpowdx_u3500sve
#define yfastpow_u3500 Sleef_finz_fastpowdx_u3500sve
#define xasinh Sleef_asinhdx_u10sve
#define yasinh Sleef_finz_asinhdx_u10sve
#define xacosh Sleef_acoshdx_u10sve
#define yacosh Sleef_finz_acoshdx_u10sve
#define xatanh Sleef_atanhdx_u10sve
#define yatanh Sleef_finz_atanhdx_u10sve
#define xexp2 Sleef_exp2dx_u10sve
#define yexp2 Sleef_finz_exp2dx_u10sve
#define xexp2_u35 Sleef_exp2dx_u35sve
#define yexp2_u35 Sleef_finz_exp2dx_u35sve
#define xexp10 Sleef_exp10dx_u10sve
#define yexp10 Sleef_finz_exp10dx_u10sve
#define xexp10_u35 Sleef_exp10dx_u35sve
#define yexp10_u35 Sleef_finz_exp10dx_u35sve
#define xexpm1 Sleef_expm1dx_u10sve
#define yexpm1 Sleef_finz_expm1dx_u10sve
#define xlog10 Sleef_log10dx_u10sve
#define ylog10 Sleef_finz_log10dx_u10sve
#define xlog2 Sleef_log2dx_u10sve
#define ylog2 Sleef_finz_log2dx_u10sve
#define xlog2_u35 Sleef_log2dx_u35sve
#define ylog2_u35 Sleef_finz_log2dx_u35sve
#define xlog1p Sleef_log1pdx_u10sve
#define ylog1p Sleef_finz_log1pdx_u10sve
#define xsincospi_u05 Sleef_sincospidx_u05sve
#define ysincospi_u05 Sleef_finz_sincospidx_u05sve
#define xsincospi_u35 Sleef_sincospidx_u35sve
#define ysincospi_u35 Sleef_finz_sincospidx_u35sve
#define xsinpi_u05 Sleef_sinpidx_u05sve
#define ysinpi_u05 Sleef_finz_sinpidx_u05sve
#define xcospi_u05 Sleef_cospidx_u05sve
#define ycospi_u05 Sleef_finz_cospidx_u05sve
#define xldexp Sleef_ldexpdx_sve
#define yldexp Sleef_finz_ldexpdx_sve
#define xilogb Sleef_ilogbdx_sve
#define yilogb Sleef_finz_ilogbdx_sve
#define xfma Sleef_fmadx_sve
#define yfma Sleef_finz_fmadx_sve
#define xsqrt Sleef_sqrtdx_sve
#define ysqrt Sleef_finz_sqrtdx_sve
#define xsqrt_u05 Sleef_sqrtdx_u05sve
#define ysqrt_u05 Sleef_finz_sqrtdx_u05sve
#define xsqrt_u35 Sleef_sqrtdx_u35sve
#define ysqrt_u35 Sleef_finz_sqrtdx_u35sve
#define xhypot_u05 Sleef_hypotdx_u05sve
#define yhypot_u05 Sleef_finz_hypotdx_u05sve
#define xhypot_u35 Sleef_hypotdx_u35sve
#define yhypot_u35 Sleef_finz_hypotdx_u35sve
#define xfabs Sleef_fabsdx_sve
#define yfabs Sleef_finz_fabsdx_sve
#define xcopysign Sleef_copysigndx_sve
#define ycopysign Sleef_finz_copysigndx_sve
#define xfmax Sleef_fmaxdx_sve
#define yfmax Sleef_finz_fmaxdx_sve
#define xfmin Sleef_fmindx_sve
#define yfmin Sleef_finz_fmindx_sve
#define xfdim Sleef_fdimdx_sve
#define yfdim Sleef_finz_fdimdx_sve
#define xtrunc Sleef_truncdx_sve
#define ytrunc Sleef_finz_truncdx_sve
#define xfloor Sleef_floordx_sve
#define yfloor Sleef_finz_floordx_sve
#define xceil Sleef_ceildx_sve
#define yceil Sleef_finz_ceildx_sve
#define xround Sleef_rounddx_sve
#define yround Sleef_finz_rounddx_sve
#define xrint Sleef_rintdx_sve
#define yrint Sleef_finz_rintdx_sve
#define xnextafter Sleef_nextafterdx_sve
#define ynextafter Sleef_finz_nextafterdx_sve
#define xfrfrexp Sleef_frfrexpdx_sve
#define yfrfrexp Sleef_finz_frfrexpdx_sve
#define xexpfrexp Sleef_expfrexpdx_sve
#define yexpfrexp Sleef_finz_expfrexpdx_sve
#define xfmod Sleef_fmoddx_sve
#define yfmod Sleef_finz_fmoddx_sve
#define xremainder Sleef_remainderdx_sve
#define yremainder Sleef_finz_remainderdx_sve
#define xmodf Sleef_modfdx_sve
#define ymodf Sleef_finz_modfdx_sve
#define xlgamma_u1 Sleef_lgammadx_u10sve
#define ylgamma_u1 Sleef_finz_lgammadx_u10sve
#define xtgamma_u1 Sleef_tgammadx_u10sve
#define ytgamma_u1 Sleef_finz_tgammadx_u10sve
#define xerf_u1 Sleef_erfdx_u10sve
#define yerf_u1 Sleef_finz_erfdx_u10sve
#define xerfc_u15 Sleef_erfcdx_u15sve
#define yerfc_u15 Sleef_finz_erfcdx_u15sve
#define xgetInt Sleef_getIntdx_sve
#define ygetInt Sleef_finz_getIntdx_sve
#define xgetPtr Sleef_getPtrdx_sve
#define ygetPtr Sleef_finz_getPtrdx_sve

#define xsinf Sleef_sinfx_u35sve
#define ysinf Sleef_finz_sinfx_u35sve
#define xcosf Sleef_cosfx_u35sve
#define ycosf Sleef_finz_cosfx_u35sve
#define xsincosf Sleef_sincosfx_u35sve
#define ysincosf Sleef_finz_sincosfx_u35sve
#define xtanf Sleef_tanfx_u35sve
#define ytanf Sleef_finz_tanfx_u35sve
#define xasinf Sleef_asinfx_u35sve
#define yasinf Sleef_finz_asinfx_u35sve
#define xacosf Sleef_acosfx_u35sve
#define yacosf Sleef_finz_acosfx_u35sve
#define xatanf Sleef_atanfx_u35sve
#define yatanf Sleef_finz_atanfx_u35sve
#define xatan2f Sleef_atan2fx_u35sve
#define yatan2f Sleef_finz_atan2fx_u35sve
#define xlogf Sleef_logfx_u35sve
#define ylogf Sleef_finz_logfx_u35sve
#define xcbrtf Sleef_cbrtfx_u35sve
#define ycbrtf Sleef_finz_cbrtfx_u35sve
#define xsinf_u1 Sleef_sinfx_u10sve
#define ysinf_u1 Sleef_finz_sinfx_u10sve
#define xcosf_u1 Sleef_cosfx_u10sve
#define ycosf_u1 Sleef_finz_cosfx_u10sve
#define xsincosf_u1 Sleef_sincosfx_u10sve
#define ysincosf_u1 Sleef_finz_sincosfx_u10sve
#define xtanf_u1 Sleef_tanfx_u10sve
#define ytanf_u1 Sleef_finz_tanfx_u10sve
#define xasinf_u1 Sleef_asinfx_u10sve
#define yasinf_u1 Sleef_finz_asinfx_u10sve
#define xacosf_u1 Sleef_acosfx_u10sve
#define yacosf_u1 Sleef_finz_acosfx_u10sve
#define xatanf_u1 Sleef_atanfx_u10sve
#define yatanf_u1 Sleef_finz_atanfx_u10sve
#define xatan2f_u1 Sleef_atan2fx_u10sve
#define yatan2f_u1 Sleef_finz_atan2fx_u10sve
#define xlogf_u1 Sleef_logfx_u10sve
#define ylogf_u1 Sleef_finz_logfx_u10sve
#define xcbrtf_u1 Sleef_cbrtfx_u10sve
#define ycbrtf_u1 Sleef_finz_cbrtfx_u10sve
#define xexpf Sleef_expfx_u10sve
#define yexpf Sleef_finz_expfx_u10sve
#define xpowf Sleef_powfx_u10sve
#define ypowf Sleef_finz_powfx_u10sve
#define xsinhf Sleef_sinhfx_u10sve
#define ysinhf Sleef_finz_sinhfx_u10sve
#define xcoshf Sleef_coshfx_u10sve
#define ycoshf Sleef_finz_coshfx_u10sve
#define xtanhf Sleef_tanhfx_u10sve
#define ytanhf Sleef_finz_tanhfx_u10sve
#define xsinhf_u35 Sleef_sinhfx_u35sve
#define ysinhf_u35 Sleef_finz_sinhfx_u35sve
#define xcoshf_u35 Sleef_coshfx_u35sve
#define ycoshf_u35 Sleef_finz_coshfx_u35sve
#define xtanhf_u35 Sleef_tanhfx_u35sve
#define ytanhf_u35 Sleef_finz_tanhfx_u35sve
#define xfastsinf_u3500 Sleef_fastsinfx_u3500sve
#define yfastsinf_u3500 Sleef_finz_fastsinfx_u3500sve
#define xfastcosf_u3500 Sleef_fastcosfx_u3500sve
#define yfastcosf_u3500 Sleef_finz_fastcosfx_u3500sve
#define xfastpowf_u3500 Sleef_fastpowfx_u3500sve
#define yfastpowf_u3500 Sleef_finz_fastpowfx_u3500sve
#define xasinhf Sleef_asinhfx_u10sve
#define yasinhf Sleef_finz_asinhfx_u10sve
#define xacoshf Sleef_acoshfx_u10sve
#define yacoshf Sleef_finz_acoshfx_u10sve
#define xatanhf Sleef_atanhfx_u10sve
#define yatanhf Sleef_finz_atanhfx_u10sve
#define xexp2f Sleef_exp2fx_u10sve
#define yexp2f Sleef_finz_exp2fx_u10sve
#define xexp2f_u35 Sleef_exp2fx_u35sve
#define yexp2f_u35 Sleef_finz_exp2fx_u35sve
#define xexp10f Sleef_exp10fx_u10sve
#define yexp10f Sleef_finz_exp10fx_u10sve
#define xexp10f_u35 Sleef_exp10fx_u35sve
#define yexp10f_u35 Sleef_finz_exp10fx_u35sve
#define xexpm1f Sleef_expm1fx_u10sve
#define yexpm1f Sleef_finz_expm1fx_u10sve
#define xlog10f Sleef_log10fx_u10sve
#define ylog10f Sleef_finz_log10fx_u10sve
#define xlog2f Sleef_log2fx_u10sve
#define ylog2f Sleef_finz_log2fx_u10sve
#define xlog2f_u35 Sleef_log2fx_u35sve
#define ylog2f_u35 Sleef_finz_log2fx_u35sve
#define xlog1pf Sleef_log1pfx_u10sve
#define ylog1pf Sleef_finz_log1pfx_u10sve
#define xsincospif_u05 Sleef_sincospifx_u05sve
#define ysincospif_u05 Sleef_finz_sincospifx_u05sve
#define xsincospif_u35 Sleef_sincospifx_u35sve
#define ysincospif_u35 Sleef_finz_sincospifx_u35sve
#define xsinpif_u05 Sleef_sinpifx_u05sve
#define ysinpif_u05 Sleef_finz_sinpifx_u05sve
#define xcospif_u05 Sleef_cospifx_u05sve
#define ycospif_u05 Sleef_finz_cospifx_u05sve
#define xldexpf Sleef_ldexpfx_sve
#define yldexpf Sleef_finz_ldexpfx_sve
#define xilogbf Sleef_ilogbfx_sve
#define yilogbf Sleef_finz_ilogbfx_sve
#define xfmaf Sleef_fmafx_sve
#define yfmaf Sleef_finz_fmafx_sve
#define xsqrtf Sleef_sqrtfx_sve
#define ysqrtf Sleef_finz_sqrtfx_sve
#define xsqrtf_u05 Sleef_sqrtfx_u05sve
#define ysqrtf_u05 Sleef_finz_sqrtfx_u05sve
#define xsqrtf_u35 Sleef_sqrtfx_u35sve
#define ysqrtf_u35 Sleef_finz_sqrtfx_u35sve
#define xhypotf_u05 Sleef_hypotfx_u05sve
#define yhypotf_u05 Sleef_finz_hypotfx_u05sve
#define xhypotf_u35 Sleef_hypotfx_u35sve
#define yhypotf_u35 Sleef_finz_hypotfx_u35sve
#define xfabsf Sleef_fabsfx_sve
#define yfabsf Sleef_finz_fabsfx_sve
#define xcopysignf Sleef_copysignfx_sve
#define ycopysignf Sleef_finz_copysignfx_sve
#define xfmaxf Sleef_fmaxfx_sve
#define yfmaxf Sleef_finz_fmaxfx_sve
#define xfminf Sleef_fminfx_sve
#define yfminf Sleef_finz_fminfx_sve
#define xfdimf Sleef_fdimfx_sve
#define yfdimf Sleef_finz_fdimfx_sve
#define xtruncf Sleef_truncfx_sve
#define ytruncf Sleef_finz_truncfx_sve
#define xfloorf Sleef_floorfx_sve
#define yfloorf Sleef_finz_floorfx_sve
#define xceilf Sleef_ceilfx_sve
#define yceilf Sleef_finz_ceilfx_sve
#define xroundf Sleef_roundfx_sve
#define yroundf Sleef_finz_roundfx_sve
#define xrintf Sleef_rintfx_sve
#define yrintf Sleef_finz_rintfx_sve
#define xnextafterf Sleef_nextafterfx_sve
#define ynextafterf Sleef_finz_nextafterfx_sve
#define xfrfrexpf Sleef_frfrexpfx_sve
#define yfrfrexpf Sleef_finz_frfrexpfx_sve
#define xexpfrexpf Sleef_expfrexpfx_sve
#define yexpfrexpf Sleef_finz_expfrexpfx_sve
#define xfmodf Sleef_fmodfx_sve
#define yfmodf Sleef_finz_fmodfx_sve
#define xremainderf Sleef_remainderfx_sve
#define yremainderf Sleef_finz_remainderfx_sve
#define xmodff Sleef_modffx_sve
#define ymodff Sleef_finz_modffx_sve
#define xlgammaf_u1 Sleef_lgammafx_u10sve
#define ylgammaf_u1 Sleef_finz_lgammafx_u10sve
#define xtgammaf_u1 Sleef_tgammafx_u10sve
#define ytgammaf_u1 Sleef_finz_tgammafx_u10sve
#define xerff_u1 Sleef_erffx_u10sve
#define yerff_u1 Sleef_finz_erffx_u10sve
#define xerfcf_u15 Sleef_erfcfx_u15sve
#define yerfcf_u15 Sleef_finz_erfcfx_u15sve
#define xgetIntf Sleef_getIntfx_sve
#define ygetIntf Sleef_finz_getIntfx_sve
#define xgetPtrf Sleef_getPtrfx_sve
#define ygetPtrf Sleef_finz_getPtrfx_sve

#else //#ifndef DETERMINISTIC

#define xsin Sleef_finz_sindx_u35sve
#define xcos Sleef_finz_cosdx_u35sve
#define xsincos Sleef_finz_sincosdx_u35sve
#define xtan Sleef_finz_tandx_u35sve
#define xasin Sleef_finz_asindx_u35sve
#define xacos Sleef_finz_acosdx_u35sve
#define xatan Sleef_finz_atandx_u35sve
#define xatan2 Sleef_finz_atan2dx_u35sve
#define xlog Sleef_finz_logdx_u35sve
#define xcbrt Sleef_finz_cbrtdx_u35sve
#define xsin_u1 Sleef_finz_sindx_u10sve
#define xcos_u1 Sleef_finz_cosdx_u10sve
#define xsincos_u1 Sleef_finz_sincosdx_u10sve
#define xtan_u1 Sleef_finz_tandx_u10sve
#define xasin_u1 Sleef_finz_asindx_u10sve
#define xacos_u1 Sleef_finz_acosdx_u10sve
#define xatan_u1 Sleef_finz_atandx_u10sve
#define xatan2_u1 Sleef_finz_atan2dx_u10sve
#define xlog_u1 Sleef_finz_logdx_u10sve
#define xcbrt_u1 Sleef_finz_cbrtdx_u10sve
#define xexp Sleef_finz_expdx_u10sve
#define xpow Sleef_finz_powdx_u10sve
#define xsinh Sleef_finz_sinhdx_u10sve
#define xcosh Sleef_finz_coshdx_u10sve
#define xtanh Sleef_finz_tanhdx_u10sve
#define xsinh_u35 Sleef_finz_sinhdx_u35sve
#define xcosh_u35 Sleef_finz_coshdx_u35sve
#define xtanh_u35 Sleef_finz_tanhdx_u35sve
#define xfastsin_u3500 Sleef_finz_fastsindx_u3500sve
#define xfastcos_u3500 Sleef_finz_fastcosdx_u3500sve
#define xfastpow_u3500 Sleef_finz_fastpowdx_u3500sve
#define xasinh Sleef_finz_asinhdx_u10sve
#define xacosh Sleef_finz_acoshdx_u10sve
#define xatanh Sleef_finz_atanhdx_u10sve
#define xexp2 Sleef_finz_exp2dx_u10sve
#define xexp2_u35 Sleef_finz_exp2dx_u35sve
#define xexp10 Sleef_finz_exp10dx_u10sve
#define xexp10_u35 Sleef_finz_exp10dx_u35sve
#define xexpm1 Sleef_finz_expm1dx_u10sve
#define xlog10 Sleef_finz_log10dx_u10sve
#define xlog2 Sleef_finz_log2dx_u10sve
#define xlog2_u35 Sleef_finz_log2dx_u35sve
#define xlog1p Sleef_finz_log1pdx_u10sve
#define xsincospi_u05 Sleef_finz_sincospidx_u05sve
#define xsincospi_u35 Sleef_finz_sincospidx_u35sve
#define xsinpi_u05 Sleef_finz_sinpidx_u05sve
#define xcospi_u05 Sleef_finz_cospidx_u05sve
#define xldexp Sleef_finz_ldexpdx_sve
#define xilogb Sleef_finz_ilogbdx_sve
#define xfma Sleef_finz_fmadx_sve
#define xsqrt Sleef_finz_sqrtdx_sve
#define xsqrt_u05 Sleef_finz_sqrtdx_u05sve
#define xsqrt_u35 Sleef_finz_sqrtdx_u35sve
#define xhypot_u05 Sleef_finz_hypotdx_u05sve
#define xhypot_u35 Sleef_finz_hypotdx_u35sve
#define xfabs Sleef_finz_fabsdx_sve
#define xcopysign Sleef_finz_copysigndx_sve
#define xfmax Sleef_finz_fmaxdx_sve
#define xfmin Sleef_finz_fmindx_sve
#define xfdim Sleef_finz_fdimdx_sve
#define xtrunc Sleef_finz_truncdx_sve
#define xfloor Sleef_finz_floordx_sve
#define xceil Sleef_finz_ceildx_sve
#define xround Sleef_finz_rounddx_sve
#define xrint Sleef_finz_rintdx_sve
#define xnextafter Sleef_finz_nextafterdx_sve
#define xfrfrexp Sleef_finz_frfrexpdx_sve
#define xexpfrexp Sleef_finz_expfrexpdx_sve
#define xfmod Sleef_finz_fmoddx_sve
#define xremainder Sleef_finz_remainderdx_sve
#define xmodf Sleef_finz_modfdx_sve
#define xlgamma_u1 Sleef_finz_lgammadx_u10sve
#define xtgamma_u1 Sleef_finz_tgammadx_u10sve
#define xerf_u1 Sleef_finz_erfdx_u10sve
#define xerfc_u15 Sleef_finz_erfcdx_u15sve
#define xgetInt Sleef_finz_getIntdx_sve
#define xgetPtr Sleef_finz_getPtrdx_sve

#define xsinf Sleef_finz_sinfx_u35sve
#define xcosf Sleef_finz_cosfx_u35sve
#define xsincosf Sleef_finz_sincosfx_u35sve
#define xtanf Sleef_finz_tanfx_u35sve
#define xasinf Sleef_finz_asinfx_u35sve
#define xacosf Sleef_finz_acosfx_u35sve
#define xatanf Sleef_finz_atanfx_u35sve
#define xatan2f Sleef_finz_atan2fx_u35sve
#define xlogf Sleef_finz_logfx_u35sve
#define xcbrtf Sleef_finz_cbrtfx_u35sve
#define xsinf_u1 Sleef_finz_sinfx_u10sve
#define xcosf_u1 Sleef_finz_cosfx_u10sve
#define xsincosf_u1 Sleef_finz_sincosfx_u10sve
#define xtanf_u1 Sleef_finz_tanfx_u10sve
#define xasinf_u1 Sleef_finz_asinfx_u10sve
#define xacosf_u1 Sleef_finz_acosfx_u10sve
#define xatanf_u1 Sleef_finz_atanfx_u10sve
#define xatan2f_u1 Sleef_finz_atan2fx_u10sve
#define xlogf_u1 Sleef_finz_logfx_u10sve
#define xcbrtf_u1 Sleef_finz_cbrtfx_u10sve
#define xexpf Sleef_finz_expfx_u10sve
#define xpowf Sleef_finz_powfx_u10sve
#define xsinhf Sleef_finz_sinhfx_u10sve
#define xcoshf Sleef_finz_coshfx_u10sve
#define xtanhf Sleef_finz_tanhfx_u10sve
#define xsinhf_u35 Sleef_finz_sinhfx_u35sve
#define xcoshf_u35 Sleef_finz_coshfx_u35sve
#define xtanhf_u35 Sleef_finz_tanhfx_u35sve
#define xfastsinf_u3500 Sleef_finz_fastsinfx_u3500sve
#define xfastcosf_u3500 Sleef_finz_fastcosfx_u3500sve
#define xfastpowf_u3500 Sleef_finz_fastpowfx_u3500sve
#define xasinhf Sleef_finz_asinhfx_u10sve
#define xacoshf Sleef_finz_acoshfx_u10sve
#define xatanhf Sleef_finz_atanhfx_u10sve
#define xexp2f Sleef_finz_exp2fx_u10sve
#define xexp2f_u35 Sleef_finz_exp2fx_u35sve
#define xexp10f Sleef_finz_exp10fx_u10sve
#define xexp10f_u35 Sleef_finz_exp10fx_u35sve
#define xexpm1f Sleef_finz_expm1fx_u10sve
#define xlog10f Sleef_finz_log10fx_u10sve
#define xlog2f Sleef_finz_log2fx_u10sve
#define xlog2f_u35 Sleef_finz_log2fx_u35sve
#define xlog1pf Sleef_finz_log1pfx_u10sve
#define xsincospif_u05 Sleef_finz_sincospifx_u05sve
#define xsincospif_u35 Sleef_finz_sincospifx_u35sve
#define xsinpif_u05 Sleef_finz_sinpifx_u05sve
#define xcospif_u05 Sleef_finz_cospifx_u05sve
#define xldexpf Sleef_finz_ldexpfx_sve
#define xilogbf Sleef_finz_ilogbfx_sve
#define xfmaf Sleef_finz_fmafx_sve
#define xsqrtf Sleef_finz_sqrtfx_sve
#define xsqrtf_u05 Sleef_finz_sqrtfx_u05sve
#define xsqrtf_u35 Sleef_finz_sqrtfx_u35sve
#define xhypotf_u05 Sleef_finz_hypotfx_u05sve
#define xhypotf_u35 Sleef_finz_hypotfx_u35sve
#define xfabsf Sleef_finz_fabsfx_sve
#define xcopysignf Sleef_finz_copysignfx_sve
#define xfmaxf Sleef_finz_fmaxfx_sve
#define xfminf Sleef_finz_fminfx_sve
#define xfdimf Sleef_finz_fdimfx_sve
#define xtruncf Sleef_finz_truncfx_sve
#define xfloorf Sleef_finz_floorfx_sve
#define xceilf Sleef_finz_ceilfx_sve
#define xroundf Sleef_finz_roundfx_sve
#define xrintf Sleef_finz_rintfx_sve
#define xnextafterf Sleef_finz_nextafterfx_sve
#define xfrfrexpf Sleef_finz_frfrexpfx_sve
#define xexpfrexpf Sleef_finz_expfrexpfx_sve
#define xfmodf Sleef_finz_fmodfx_sve
#define xremainderf Sleef_finz_remainderfx_sve
#define xmodff Sleef_finz_modffx_sve
#define xlgammaf_u1 Sleef_finz_lgammafx_u10sve
#define xtgammaf_u1 Sleef_finz_tgammafx_u10sve
#define xerff_u1 Sleef_finz_erffx_u10sve
#define xerfcf_u15 Sleef_finz_erfcfx_u15sve
#define xgetIntf Sleef_finz_getIntfx_sve
#define xgetPtrf Sleef_finz_getPtrfx_sve

#endif // #ifndef DETERMINISTIC
