/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsoftware_j_JInterface */

#ifndef _Included_com_jsoftware_j_JInterface
#define _Included_com_jsoftware_j_JInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jsoftware_j_JInterface_MTYOFM
#define com_jsoftware_j_JInterface_MTYOFM 1L
#undef com_jsoftware_j_JInterface_MTYOER
#define com_jsoftware_j_JInterface_MTYOER 2L
#undef com_jsoftware_j_JInterface_MTYOLOG
#define com_jsoftware_j_JInterface_MTYOLOG 3L
#undef com_jsoftware_j_JInterface_MTYOSYS
#define com_jsoftware_j_JInterface_MTYOSYS 4L
#undef com_jsoftware_j_JInterface_MTYOEXIT
#define com_jsoftware_j_JInterface_MTYOEXIT 5L
#undef com_jsoftware_j_JInterface_MTYOFILE
#define com_jsoftware_j_JInterface_MTYOFILE 6L
/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    getVariableNative
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_jsoftware_j_JInterface_getVariableNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    setVariableNative
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jsoftware_j_JInterface_setVariableNative
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    callJNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jsoftware_j_JInterface_callJNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    destroyJNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jsoftware_j_JInterface_destroyJNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    initializeJNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jsoftware_j_JInterface_initializeJNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    dorsNative
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsoftware_j_JInterface_dorsNative
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
