/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jsoftware_j_JInterface */

#ifndef _Included_com_jsoftware_j_JInterface
#define _Included_com_jsoftware_j_JInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jsoftware_j_JInterface_MTYOFM
#define com_jsoftware_j_JInterface_MTYOFM 1L
#undef com_jsoftware_j_JInterface_MTYOER
#define com_jsoftware_j_JInterface_MTYOER 2L
#undef com_jsoftware_j_JInterface_MTYOLOG
#define com_jsoftware_j_JInterface_MTYOLOG 3L
#undef com_jsoftware_j_JInterface_MTYOSYS
#define com_jsoftware_j_JInterface_MTYOSYS 4L
#undef com_jsoftware_j_JInterface_MTYOEXIT
#define com_jsoftware_j_JInterface_MTYOEXIT 5L
#undef com_jsoftware_j_JInterface_MTYOFILE
#define com_jsoftware_j_JInterface_MTYOFILE 6L
/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JDo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jsoftware_j_JInterface_JDo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JDoR
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsoftware_j_JInterface_JDoR
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JGetc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsoftware_j_JInterface_JGetc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JSetc
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_jsoftware_j_JInterface_JSetc
  (JNIEnv *, jclass, jstring, jstring, jlong);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jsoftware_j_JInterface_JFree
  (JNIEnv *, jclass);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JInit
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jsoftware_j_JInterface_JInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JInit2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jsoftware_j_JInterface_JInit2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JGetLocale
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jsoftware_j_JInterface_JGetLocale
  (JNIEnv *, jclass);

/*
 * Class:     com_jsoftware_j_JInterface
 * Method:    JSetEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jsoftware_j_JInterface_JSetEnv
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
